### ISSUE TITLE
Add default instance label for empty instance metrics

### ISSUE THREAD

**Issue by haosong** [wavefrontHQ/prometheus-storage-adapter#15]
We noticed that when we send metrics with empty instance tag using `pushgateway`, since the instance label will be an empty string (see here: https://github.com/prometheus/pushgateway#about-the-job-and-instance-labels), thus the Wavefront metrics will get blocked at Proxy level. So we probably should have some default instance label to avoid this from happening

**Comment by haosong** [comment]
Since `source=""` will cause parsing issue at proxy level. We either give a default value of source field, or we just don't have source field at all when the value is empty (* And we believe the 2nd way is preferred here).

**Comment by vikramraman** [comment]
Addressed by PR #14 and https://github.com/wavefrontHQ/prometheus-storage-adapter/commit/e6dd864a017e97abef6d89b4112e100eb57194c5.
