### ISSUE TITLE
Provide an option to use original metrics name

### ISSUE THREAD

**Issue by haosong** [wavefrontHQ/prometheus-storage-adapter#16]
https://github.com/wavefrontHQ/prometheus-storage-adapter/blob/master/backend/writer.go#L166
Currently, we convert every `_` in the metrics to `.`, I think there should be a flag to disable this conversion if the user wants to use the original metrics name.

**Comment by vikramraman** [comment]
Added a new `convert-paths` option (defaults to true to retain backwards compat). Setting to false will retain `_` as is without any conversions.

Addressed by https://github.com/wavefrontHQ/prometheus-storage-adapter/commit/ebbbaf4c6b528e108f447b1fa50b5bb1bda18c8f
