### ISSUE TITLE
Prebuilt binaries are not provided since 1.0.1

### ISSUE THREAD

**Issue by making** [wavefrontHQ/prometheus-storage-adapter#18]
Could you attach prebuilt binaries to the releases?

**Comment by vikramraman** [comment]
@making Thanks for raising the issue. Are you looking for binaries for any specific platforms?

**Comment by making** [comment]
Linux should be enough for me

**Comment by vikramraman** [comment]
Added binaries for the latest release v1.0.3. We'll make sure to add them for future releases. Thanks!

**Comment by making** [comment]
Thanks!
