### ISSUE TITLE
Support PodSecurityPolicy by adding numeric USER to Dockerfile

### ISSUE THREAD

**Issue by lohbe** [wavefrontHQ/prometheus-storage-adapter#19]
Hi,

I encounter the following error:
```
status:
  containerStatuses:
   state:
      waiting:
        message: container has runAsNonRoot and image has non-numeric user (nobody),
          cannot verify user is non-root
        reason: CreateContainerConfigError
```
Steps to replicate:

1. minikube 1.14.2 & K8s 1.19.2 with PSP add-on enabled, helm v3.4
2. Install WavefrontHQ helm chart: 
```
helm install prom-adapter wavefront/prometheus-storage-adapter \ 
    --namespace prom-adapter \ 
    --create-namespace \ 
    --set wavefront.wavefront.url=https://"$wavefront_url".wavefront.com \ 
    --set wavefront.wavefront.token="$wavefront_token" \ 
    --set adapter.prefix="$prefix" 
```
After deploying, the Wavefront proxy pod runs fine, but the Prometheus Storage Adapter fails:
```
ben@hades:~/local/cna-psa$ kubectl get pods -nprom-adapter
NAME                                                       READY   STATUS                       RESTARTS   AGE
prom-adapter-prometheus-storage-adapter-58ddb88f4f-pd2jk   0/1     CreateContainerConfigError   0          16m
prom-adapter-wavefront-proxy-749ff57f55-zjdnb              1/1     Running                      0          16m
```
comparing the Dockerfiles for [wavefront-proxy](https://github.com/wavefrontHQ/wavefront-proxy/blob/master/proxy/docker/Dockerfile) and [prometheus-storage-adapter](https://github.com/wavefrontHQ/prometheus-storage-adapter/blob/1.0.3/Dockerfile) shows that wavefront-proxy `USER` is set to `1000:2000`, and prometheus-storage-adapter is set to `nobody`

Please consider changing USER to a numeric number for PSP support. If not, are there any workarounds at the moment?

**Comment by helen-shao** [comment]
Hi @lohbe, we've updated the version for K8s to 1.22 recently. PSP is going through deprecation process starting 1.21 and will be fully deprecated from 1.25. 
Would you mind retry with the new release of the prometheus-storage-adapter and raise questions if this is a persistent issue?
