### ISSUE TITLE
Create new release for metrics whitelisting changes

### ISSUE THREAD

**Issue by inspiremirnal** [wavefrontHQ/prometheus-storage-adapter#24]
@mmichael @josephgee - Can you guys also create v1.0.4 release.

**Comment by inspiremirnal** [comment]
@mmichael @josephgee @ustinov @vikramraman  -- Can one of you please cut the release or give me rights to do it :) , we are in desperate need of the filter changes.

**Comment by josephgee** [comment]
@inspiremirnal Its in the works.

**Comment by josephgee** [comment]
FYI @dflorea

**Comment by akodali18** [comment]
Fixed with [PR# 23](https://github.com/wavefrontHQ/prometheus-storage-adapter/pull/23)
