### ISSUE TITLE
prometheus histograms are converted to counters

### ISSUE THREAD

**Issue by fedork** [wavefrontHQ/prometheus-storage-adapter#27]
It looks like this adapter does not recognize Prometheus histograms as such and even though Wavefront does natively support histograms they get converted to a set of regular counters with "le" label holding the bucket boundary. Looking at the source code I see that all SendMetric is used and for histograms SendDistribution should be used instead. I could not find how one can tell that a Timeseries is actually a histogram (where is the metadata?), but I believe other intergrations (Telegraf plugin) do handle it properly, so it should be possible.
Can this be fixed?

**Comment by gagan-eg** [comment]
We would be interested in this as well.

**Comment by gagan-eg** [comment]
Looks like this solves the problem of conversion on the wavefront side:
https://docs.wavefront.com/ts_cumulativeHisto.html#parameters

**Comment by johncornish** [comment]
If we understand correctly, the question you are asking is why are prometheus histograms not converted to wavefront histograms before they are sent to wavefront. If yes, I think this was intended at the time of development and you can use 
https://docs.wavefront.com/ts_cumulativeHisto.html#how-to-map-prometheus-queries-to-wavefront-queries or  https://docs.wavefront.com/ts_cumulativePercentile.html#example  to convert prometheus histograms to wavefront histograms while querying per your use case. 

Also, when you say that telegraf plugin handles it properly, could you point us to the repo you are referring to?

**Comment by johncornish** [comment]
We are tracking this internally within our ticketing system as ticket [K8SSAAS-1061](https://jira.eng.vmware.com/browse/K8SSAAS-1061) and we'll add it to our prioritization roadmap as a feature
