### ISSUE TITLE
Reconnect when downstream connection is broken

### ISSUE THREAD

**Issue by AdamJohnson100** [wavefrontHQ/prometheus-storage-adapter#4]
Running the remote storage adapter (RSA) on a deployment of Prometheus 2.5.  Restarted the proxy that this was writing to and the connection never regenerated.  Points stopped reporting to Wavefront, and the RSA wrote until the buffer was full and could not flush.

I would expect the RSA would be able to reconnect to a proxy machine if it sees the connection is dead.

This was observed when data in Wavefront was missing and Prometheus logs were spamming:

level=warn ts=2018-12-07T23:14:41.523353596Z caller=queue_manager.go:230 component=remote queue=0:http://wavefront-stg-adapter/receive msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed."
level=warn ts=2018-12-07T23:14:41.523388415Z caller=queue_manager.go:230 component=remote queue=0:http://wavefront-stg-adapter/receive msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed."

**Comment by sandeepbhojwani** [comment]
We are hitting this issue too. Please can we get a fix?

**Comment by vikramraman** [comment]
Appears this may still not be fixed in v1.0.1. @sandeepbhojwani Have you tried the fix, does it work on your end?

**Comment by sandeepbhojwani** [comment]
There's a second issue i found that causes this. Connection is not checked for staleness before returning to the pool. I will submit a PR to add the staleness check.
