### ISSUE TITLE
Prometheus storage adapter is inconsistent in scraping metrics

### ISSUE THREAD

**Issue by gangadharaswamy** [wavefrontHQ/prometheus-storage-adapter#7]
Prometheus storage adapter binaries are inconsistent in scraping metrics from prometheus.
Tested [binaries](https://github.com/wavefrontHQ/prometheus-storage-adapter/releases) on three Kubernetes environments. Adapter failed to collect metrics on all env's.

Locally built the linux version of adapter and tested on same Kubernetes environments. Out of three env's, adapter was able to collect metrics on two env's and failed to collect on one env. Don't know the exact reason for such behaviour. Adapter is expected to work on all environments.

**Comment by prydin** [comment]
Can you please attach some logs? Also, when you say "failed to collect" what do you mean? Just that you didn't get any metrics or did you see an error message?

**Comment by gangadharaswamy** [comment]
When the adapter fails to collect, we don't get any metrics and no error messages also. Currently I don't have any logs, will try to get it.

**Comment by prydin** [comment]
Not a bug. Turned out to be an issue with the prometheus configuration.
